### ISSUE TITLE
Load list of your projects from Github API

### ISSUE THREAD

**Issue by pavelbinar** [zdenekpribyla/developer-profile#3]
```
https://api.github.com/users/zdenekpribyla/repos
```

More info: https://developer.github.com/v3/repos/#list-user-repositories

**Comment by zdenekpribyla** [comment]
https://github.com/zdenekpribyla/developer-profile/commit/16115484335cb63be1e619ceca69dfa7c98d2c0b

**Comment by zdenekpribyla** [comment]
7598831809a8c4dabeab5f987512b86faea80d5b  this is final version => loading data from local .json file (instead of GitHub)
